apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-solr-index-rebuild
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ckan
              image: {{ .Values.ckan.image }}
              imagePullPolicy: Always
              command: [ ckan, datagovuk, reindex-recent ]
              env:
                {{- include "ckan.environment-variables" . | nindent 16 }}
              volumeMounts:
                - name: production-ini
                  mountPath: /config
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: production-ini
              configMap:
                name: {{ .Release.Name }}-ckan-production-ini
