apiVersion: v1
kind: Secret
metadata:
  name: ckan
type: Opaque
stringData:
  sqlalchemy_url: "postgresql://ckan:ckan@ckan-test-postgres/ckan"
  solr_password: "ckan"
  smtp_password: "ckan"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
