ckan:
  count: 1
  image: ghcr.io/kentsanggds/ckan:2.9.7
  serviceAccount:
    enabled: false
    iamRoleARN: ""
  config:
    site:
      id: "dgu"
      url: "http://dev.data.gov.uk:8081"
      title: "dev.data.gov.uk"
      description: "Data publisher"
    mock_harvest_source: "https://ckan-static-mock-harvest-source.cloudapps.digital/"
    sqlalchemyUrlSecretKeyRef:
      name: ckan
      key: sqlalchemy_url
    dbHost: ""
    redis:
      host: ""
      port: "6379"
      db_number: "1"
    beakerSessionSecretKeyRef:
      name: ckan
      key: beaker_session_secret
    solr:
      url: ""
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: solr_password
    smtp:
      server: "localhost:1025"
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: smtp_password
      mailFrom: ""
      starttls: "False"
    s3:
      useIamServiceAccount: false
      bucketName: ""
      urlPrefix: ""
      regionName: ""
      credentials:
        awsAccessKeyIdSecretKeyRef:
          name: ckan
          key: aws_access_key_id
        awsSecretAccessKeySecretKeyRef:
          name: ckan
          key: aws_secret_access_key
    

solr:
  enabled: true
  image: ghcr.io/samsimpson1/solr
  persistence:
    enabled: false
    persistentVolumeClaimName: "solr"
# This postgres instance is for development purposes only
postgres:
  enabled: true
  image: ghcr.io/samsimpson1/postgis
  persistence:
    enabled: false
    persistentVolumeClaimName: "postgres"
redis:
  enabled: true
  image: redis:6.2.5-alpine3.14
ingress:
  enabled: true
  host: dev.data.gov.uk
  ingressClassName: ""
  annotations:
  tls:
    enabled: false
dev:
  enabled: true
gather:
  count: 1
fetch:
  count: 1
  
pycsw:
  count: 1
  image: ghcr.io/geopython/pycsw
  ingress:
    enabled: true
    host: pycsw.data.gov.uk
    ingressClassName: ""
    annotations:
    tls:
      enabled: false
