apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-solr-index-rebuild
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ckan
              image: {{ .Values.ckan.image }}
              command: [ ckan, search-index, rebuild ]
          restartPolicy: OnFailure
