apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Release.Name }}-ckan
spec:
  replicas: {{ .Values.ckan.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ckan
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ckan
    spec:
      containers:
        - name: ckan
          image: {{ .Values.ckan.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: production-ini
              mountPath: /config
              readOnly: true
          command: ["/bin/sh", "-c"]
          args: ["/ckan-entrypoint.sh && ckan run --host 0.0.0.0"]
          env:
            {{ include "ckan.environment-variables" . | nindent 12 }}
      volumes:
        - name: production-ini
          configMap:
            name: {{ .Release.Name }}-ckan-production-ini
