{{- if .Values.ckan.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ckan-service-account-{{ .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ckan.serviceAccount.iamRoleARN }}
{{- end }}
