ckanHelmValues:
  environment: production
  ckan:
    args: ["gunicorn --bind 0.0.0.0:5000 wsgi:application --timeout 120"]
    probes:
      enabled: false
    config:
      site:
        url: "https://ckan.publishing.service.gov.uk"
        title: "data.gov.uk"
      dbHost: "ckan-postgres.production.govuk-internal.digital"
      redis:
        host: "backend-redis.production.govuk-internal.digital"
      smtp:
        server: "email-smtp.eu-west-1.amazonaws.com:587"
        user: "AKIASQDMCZ2EZRPSFZRO"
        mailFrom: "team@data.gov.uk"
        starttls: "True"
      s3:
        useIamServiceAccount: true
        bucketName: "datagovuk-production-ckan-organogram"
        regionName: "eu-west-1"
        urlPrefix: "https://s3-eu-west-1.amazonaws.com/datagovuk-production-ckan-organogram/"
    serviceAccount:
      enabled: true
      name: ckan
      iamRoleARN: arn:aws:iam::172025368201:role/ckan-govuk
  pycsw:
    count: 1
    args: ["gunicorn --bind 0.0.0.0:8000 wsgi:application --timeout 120"]
    probes:
      enabled: true
  solr:
    enabled: true
    persistence:
      enabled: true
      persistentVolumeClaimName: solr
  postgres:
    enabled: false
  redis:
    enabled: false
  ingress:
    host: ckan.publishing.service.gov.uk
    ingressClassName: aws-alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/inbound-cidrs: 51.149.8.0/25, 52.208.24.161/32
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:172025368201:certificate/b315cd63-5ca1-4c7b-8d3b-914eccc024f8"
    tls:
      enabled: true
  dev:
    enabled: false
  gather:
    count: 1
  fetch:
    count: 1
  externalSecret:
    enabled: true
