apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ckan-init
data:
  init.sh: |
    # copy ckan.ini
    cp /map/ckan.ini /config

    # update ckan.ini
    ckan config-tool $CKAN_INI "beaker.session.secret=$CKAN_BEAKER_SESSION_SECRET"
    ckan config-tool $CKAN_INI "ckan.i18n_directory=$CKAN_VENV/src/ckanext-datagovuk/ckanext/datagovuk"

    {{- if $.Values.dev.enabled }}
    ckan config-tool $CKAN_INI "ckan.datagovuk.s3_aws_access_key_id = $CKAN_AWS_ACCESS_KEY_ID"
    ckan config-tool $CKAN_INI "ckan.datagovuk.s3_aws_secret_access_key = $CKAN_AWS_ACCESS_KEY_SECRET"
    {{- end }}

    /ckan-entrypoint.sh
