{{- if .Values.solr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      {{- if .Values.solr.persistence.enabled }}
      initContainers:
        - name: fix-volume-permissions
          image: {{ .Values.solr.image }}
          command: [ bash, -c, "chown -R solr:solr /data" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: data
              mountPath: /data
      {{- end }}
      containers:
        - name: solr
          image: {{ .Values.solr.image }}
          ports:
            - name: solr
              containerPort: 8983
          {{- if .Values.solr.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /opt/solr/server/solr/ckan/data
          {{- end }}
      {{- if .Values.solr.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.solr.persistence.persistentVolumeClaimName }}
      {{- end }}
{{- end }}
