apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pycsw
spec:
  replicas: {{ .Values.pycsw.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pycsw
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pycsw
    spec:
      {{- include "ckan.pycsw-init" . | nindent 6 }}
      containers:
        - name: pycsw
          image: {{ .Values.pycsw.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config
          command: ["/bin/sh", "-c", "python $CKAN_VENV/src/pycsw/pycsw/wsgi.py"]
          env:
            - name: PYCSW_CONFIG
              value: /config/pycsw.cfg
            {{ include "ckan.environment-variables" . | nindent 12 }}
      {{ include "ckan.pycsw-volumes" . | nindent 6 }}
