apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Release.Name }}-pycsw
spec:
  replicas: {{ .Values.pycsw.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pycsw
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pycsw
    spec:
      initContainers:
        - name: config-set
          image: {{ .Values.ckan.image }}
          command: [ "/bin/sh", "-c", '. /init/init.sh']
          imagePullPolicy: Always
          env:
            {{ include "ckan.environment-variables" . | nindent 12 }}
            - name: CKAN_BEAKER_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ckan.config.beakerSessionSecretKeyRef.name }}
                  key: {{ .Values.ckan.config.beakerSessionSecretKeyRef.key }}
          volumeMounts:
            - name: pycsw-cfg
              mountPath: /pycsw
              readOnly: true
            - name: production-ini
              mountPath: /map
              readOnly: true
            - name: config
              mountPath: /config
            - name: pycsw-init
              mountPath: /init
      containers:
        - name: pycsw
          image: {{ .Values.pycsw.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config
          command: ["/bin/sh", "-c", "python $CKAN_VENV/src/pycsw/pycsw/wsgi.py"]
          env:
            - name: PYCSW_CONFIG
              value: /config/pycsw.cfg
            {{ include "ckan.environment-variables" . | nindent 12 }}
      volumes:
        - name: pycsw-cfg
          configMap:
            name: {{ .Release.Name }}-pycsw-cfg
        - name: pycsw-init
          configMap:
            name: {{ .Release.Name }}-pycsw-init
        - name: production-ini
          configMap:
            name: {{ .Release.Name }}-ckan-production-ini
        - name: config
          emptyDir: {}
